### ISSUE TITLE
sumo_source_local_file broken on 1.2.19

### ISSUE THREAD

**Issue by zts** [SumoLogic/sumologic-collector-chef-cookbook#119]
The change introduced by PR 118/113/112 seems to be broken - I can't easily run the tests in this cookbook, so I can't tell whether this is only a problem in my environment.

However, the error I'm getting is:

```
           ================================================================================
           Error executing action `create` on resource 'sumo_source_local_file[var_logging]'
           ================================================================================

           ArgumentError
           -------------
           Property Create /etc/sumologic/var_logging.json is not defined in class sumo_source_local_file[var_logging]

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/sumologic-collector/libraries/provider_source.rb:21:in `block in <class:SumoSource>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/el-sumologic/recipes/collector.rb

           146:   sumo_source_local_file 'var_logging' do
           147:     source_name 'var_logging'
           148:     category "#{account_name}/#{env}/var_logging"
           149:     automatic_date_parsing true
           150:     multiline_processing_enabled false
           151:     use_autoline_matching false
           152:     force_time_zone true
           153:     time_zone 'UTC'
           154:     source_json_directory node['sumologic']['sumo_json_path']
           155:     path_expression '/var/logging/archive/*/*/*.csv'
           156:   end
           157: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/el-sumologic/recipes/collector.rb:146:in `from_file'

           sumo_source_local_file("var_logging") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :sumo_source_local_file
             cookbook_name "el-sumologic"
             recipe_name "collector"
             source_name "var_logging"
             category "elastera/kitchen/var_logging"
             automatic_date_parsing true
             force_time_zone true
             time_zone "UTC"
             source_json_directory "/etc/sumologic"
             path_expression "/var/logging/archive/*/*/*.csv"
           end
```

The code in question is `converge_if_changed("Create #{source_json_path}") do`, but that does not seem like the correct way to call `converge_if_changed` - the docs say that the (optional) argument should be a list of (symbolic) property names, not a string: http://www.rubydoc.info/gems/chef/Chef%2FProvider%3Aconverge_if_changed

**Comment by acranox** [comment]
I'm seeing the same problem.  I was just about to open an issue, but you got to it first.

**Comment by dannenberg** [comment]
I'm also seeing this problem. I wonder if it is related to my "fix" for https://github.com/SumoLogic/sumologic-collector-chef-cookbook/issues/112 which they merged last night

**Comment by duchatran** [comment]
Sorry guys, my bad - somehow the PR passed the tests. What's the best way to fix this, revert or just submit a new PR to fix this?

**Comment by dannenberg** [comment]
Probably best to revert. I don't know of an appropriate fix offhand, sorry.

**Comment by sean-hart** [comment]
What is the status of cutting to supermarket?

**Comment by duchatran** [comment]
1.2.20 is now available on supermarket - closing this issue.
