### ISSUE TITLE
Missing credentials despite having them in data bag

### ISSUE THREAD

**Issue by cleung2010** [SumoLogic/sumologic-collector-chef-cookbook#81]
I am encountering an error with the installation of the collector even though I have the credentials set via encrypted data bag through `['sumologic']['credentials']`. I have verified that the values exists by adding `puts` for `item['access_id']` and `item['access_key']` right after [sumoconf.rb#L43](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/recipes/sumoconf.rb#L43).

```
 
================================================================================
Error executing action `install_and_configure` on resource 'sumologic_collector[/opt/SumoCollector]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[Install Sumo Collector] (/var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/cookbooks/sumologic-collector/providers/default.rb line 140) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/sumocollector -console -q -dir /opt/SumoCollector -Vcollector.name=ids-consul-devqasicecns002 -VsyncSources=/etc/sumo.d/sumo-sources.json ----
STDOUT: Unpacking JRE ...
Preparing JRE ...
Starting Installer ...
The installation directory has been set to /opt/SumoCollector.
Extracting files...
Missing credentials in quiet mode installation.  Please reinstall with credentials.
Rolling back changes...
STDERR: Jun 16, 2016 8:05:39 PM java.util.prefs.FileSystemPreferences$2 run
INFO: Created system preferences directory in java.home.
---- End output of /var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/sumocollector -console -q -dir /opt/SumoCollector -Vcollector.name=ids-consul-devqasicecns002 -VsyncSources=/etc/sumo.d/sumo-sources.json ----
Ran /var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/sumocollector -console -q -dir /opt/SumoCollector -Vcollector.name=ids-consul-devqasicecns002 -VsyncSources=/etc/sumo.d/sumo-sources.json returned 1
 
Cookbook Trace:
---------------
/var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
/var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
 
Resource Declaration:
---------------------
# In /var/chef/runs/4fcf1ebe-20b7-4663-8bec-05c20314aad8/local-mode-cache/cache/cookbooks/ids_consul/recipes/sumologic.rb
 
34: sumologic_collector '/opt/SumoCollector' do
35:   collector_name "ids-consul-#{node['hostname']}"
36:   sync_sources '/etc/sumo.d/sumo-sources.json'
37: end
38: 
```

**Comment by duchatran** [comment]
@cleung2010 : Sorry to hear about this issue. Based on this: 
`sumocollector -console -q -dir /opt/SumoCollector -Vcollector.name=ids-consul-devqasicecns002 -VsyncSources=/etc/sumo.d/sumo-sources.json 
`

it appears there is no reference to the credential information, please refer to this doc: http://help.sumologic.com/Send_Data/Installed_Collectors/Step_4._Install_the_Collector/02_Quiet_Mode_Installation_Method
for required flags

**Comment by zl4bv** [comment]
The values in the `sumologic_collector::sumoconf` recipe are not applied to the `sumologic_collector` resource. If you are using the resource directly then try something like this:

```ruby
secret = Chef::EncryptedDataBagItem.load_secret(creds['secret_file'])
item = Chef::EncryptedDataBagItem.load(creds['bag_name'], creds['item_name'], secret)

sumologic_collector '/opt/SumoCollector' do
  collector_name    "ids-consul-#{node['hostname']}"
  sync_sources      '/etc/sumo.d/sumo-sources.json'
  sumo_access_id    item['access_id']
  sumo_access_key   item['access_key']
end
```

Ideally the recipe should be updated to pass them to the resource.

**Comment by duchatran** [comment]
@cleung2010: I am closing this issue, feel free to reopen if you have more questions
